eureka:
  client:
    service-url:
      defaultZone: http://eureka1.bs.feuler.cn:8761/eureka/,http://eureka2.bs.feuler.cn:8762/eureka/,http://eureka3.bs.feuler.cn:8763/eureka/

  server:
    enable-self-preservation: false
  instance:
    hostname: eureka1.bs.feuler.cn

spring:
  application:
    name: eureka

server:
  port: 8761
#########################################################################################
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka1.bs.feuler.cn:8761/eureka/,http://eureka2.bs.feuler.cn:8762/eureka/,http://eureka3.bs.feuler.cn:8763/eureka/
#
#  server:
#    enable-self-preservation: false
#  instance:
#    hostname: eureka2.bs.feuler.cn
#
#spring:
#  application:
#    name: eureka
#
#server:
#  port: 8762
###################################################################################
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka1.bs.feuler.cn:8761/eureka/,http://eureka2.bs.feuler.cn:8762/eureka/,http://eureka3.bs.feuler.cn:8763/eureka/
#
#  server:
#    enable-self-preservation: false
#  instance:
#    hostname: eureka3.bs.feuler.cn
#
#spring:
#  application:
#    name: eureka
#
#server:
#  port: 8763